# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable
Bundler:
  Enabled: true
Gemspec:
  Enabled: false
Layout:
  Enabled: true
Lint:
  Enabled: true
Metrics:
  Enabled: true
Naming:
  Enabled: true
Performance:
  Enabled: true
  Exclude:
    - "test/**/*"
Rails:
  Enabled: true
Security:
  Enabled: true
Style:
  Enabled: true

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
